"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-05 12:11:28.763579
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('raw_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_files_sha256'), ['sha256'], unique=True)

    op.create_table('server_file_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mtime_ns', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('mfa_pending', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('product_code', sa.String(length=64), nullable=True),
    sa.Column('serial', sa.String(length=64), nullable=False),
    sa.Column('firmware', sa.String(length=255), nullable=True),
    sa.Column('series', sa.String(length=64), nullable=True),
    sa.Column('device_type', sa.String(length=32), nullable=True),
    sa.Column('data_format', sa.String(length=128), nullable=True),
    sa.Column('parser', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('identification', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'manufacturer', 'serial', name='uq_device_owner_serial')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_owner_id'), ['owner_id'], unique=False)

    op.create_table('imports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('uploaded_bytes', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_imports_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_imports_status'), ['status'], unique=False)

    op.create_table('device_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('rel_path', sa.String(length=1024), nullable=False),
    sa.Column('raw_file_id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'rel_path', 'raw_file_id', name='uq_device_file_version')
    )
    with op.batch_alter_table('device_files', schema=None) as batch_op:
        batch_op.create_index('ix_device_files_device_path', ['device_id', 'rel_path'], unique=False)

    op.create_table('import_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('sd_path', sa.String(length=1024), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('raw_file_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_files_import_id'), ['import_id'], unique=False)

    op.create_table('nights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_ms', sa.BigInteger(), nullable=True),
    sa.Column('end_ms', sa.BigInteger(), nullable=True),
    sa.Column('usage_s', sa.Float(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('has_detail', sa.Boolean(), nullable=False),
    sa.Column('has_summary', sa.Boolean(), nullable=False),
    sa.Column('parser', sa.String(length=32), nullable=False),
    sa.Column('parser_version', sa.String(length=16), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('summary_raw', sa.JSON(), nullable=False),
    sa.Column('mask_intervals', sa.JSON(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('storage_gen', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_import_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'date', name='uq_night_device_date')
    )
    with op.batch_alter_table('nights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nights_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_nights_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nights_owner_id'), ['owner_id'], unique=False)

    op.create_table('night_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('night_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['night_id'], ['nights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('night_id', 'key', 'source', name='uq_night_metric')
    )
    with op.batch_alter_table('night_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_metric_key_value', ['key', 'value'], unique=False)
        batch_op.create_index(batch_op.f('ix_night_metrics_night_id'), ['night_id'], unique=False)

    op.create_table('night_source_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('night_id', sa.Integer(), nullable=False),
    sa.Column('rel_path', sa.String(length=1024), nullable=False),
    sa.Column('raw_file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['night_id'], ['nights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('night_source_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_night_source_files_night_id'), ['night_id'], unique=False)

    op.create_table('therapy_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('night_id', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.BigInteger(), nullable=False),
    sa.Column('end_ms', sa.BigInteger(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['night_id'], ['nights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('therapy_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_therapy_sessions_night_id'), ['night_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('night_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('onset_ms', sa.BigInteger(), nullable=False),
    sa.Column('start_ms', sa.BigInteger(), nullable=False),
    sa.Column('end_ms', sa.BigInteger(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('source_file', sa.String(length=1024), nullable=False),
    sa.Column('raw_file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['night_id'], ['nights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_files.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['therapy_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_code'), ['code'], unique=False)
        batch_op.create_index('ix_events_night_start', ['night_id', 'start_ms'], unique=False)

    op.create_table('signal_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('night_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('sample_rate', sa.Float(), nullable=False),
    sa.Column('start_ms', sa.BigInteger(), nullable=False),
    sa.Column('end_ms', sa.BigInteger(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('gain', sa.Float(), nullable=False),
    sa.Column('offset', sa.Float(), nullable=False),
    sa.Column('invalid_digital', sa.Integer(), nullable=True),
    sa.Column('physical_min', sa.Float(), nullable=False),
    sa.Column('physical_max', sa.Float(), nullable=False),
    sa.Column('vmin', sa.Float(), nullable=True),
    sa.Column('vmax', sa.Float(), nullable=True),
    sa.Column('vmean', sa.Float(), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('source_file', sa.String(length=1024), nullable=False),
    sa.Column('raw_file_id', sa.Integer(), nullable=True),
    sa.Column('conversion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['night_id'], ['nights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_files.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['therapy_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_segments', schema=None) as batch_op:
        batch_op.create_index('ix_segments_night_channel', ['night_id', 'channel'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signal_segments', schema=None) as batch_op:
        batch_op.drop_index('ix_segments_night_channel')

    op.drop_table('signal_segments')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_night_start')
        batch_op.drop_index(batch_op.f('ix_events_code'))

    op.drop_table('events')
    with op.batch_alter_table('therapy_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_therapy_sessions_night_id'))

    op.drop_table('therapy_sessions')
    with op.batch_alter_table('night_source_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_night_source_files_night_id'))

    op.drop_table('night_source_files')
    with op.batch_alter_table('night_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_night_metrics_night_id'))
        batch_op.drop_index('ix_metric_key_value')

    op.drop_table('night_metrics')
    with op.batch_alter_table('nights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nights_owner_id'))
        batch_op.drop_index(batch_op.f('ix_nights_device_id'))
        batch_op.drop_index(batch_op.f('ix_nights_date'))

    op.drop_table('nights')
    with op.batch_alter_table('import_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_files_import_id'))

    op.drop_table('import_files')
    with op.batch_alter_table('device_files', schema=None) as batch_op:
        batch_op.drop_index('ix_device_files_device_path')

    op.drop_table('device_files')
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imports_status'))
        batch_op.drop_index(batch_op.f('ix_imports_owner_id'))
        batch_op.drop_index(batch_op.f('ix_imports_created_at'))

    op.drop_table('imports')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_owner_id'))

    op.drop_table('devices')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('server_file_index')
    with op.batch_alter_table('raw_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_files_sha256'))

    op.drop_table('raw_files')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
