"""hardware

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 13:07:49.558735
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('size', sa.String(length=32), nullable=True),
    sa.Column('serial', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('replace_after_days', sa.Integer(), nullable=True),
    sa.Column('expected_hours', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hardware_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hardware_items_owner_id'), ['owner_id'], unique=False)

    op.create_table('hardware_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('read_on', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['hardware_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hardware_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hardware_readings_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hardware_readings_item_id'))

    op.drop_table('hardware_readings')
    with op.batch_alter_table('hardware_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hardware_items_owner_id'))

    op.drop_table('hardware_items')
    # ### end Alembic commands ###
