"""app sessions

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 14:04:43.649685
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=8), server_default='web', nullable=False))
        batch_op.add_column(sa.Column('device_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_column('device_name')
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
